# Generated by Django 5.2.4 on 2025-08-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.category'),
        ),
    ]
